FROM rust:1.64

# 2. Copy the files in your machine to the Docker image
COPY ./ ./

# Build the client for release
RUN cargo build --release --bin zkp-server

# Run the binary
CMD ["./target/release/zkp-server"]